config/routes.rb
Rails.application.routes.draw do

  root :to => "items#index"
  get '/about' => 'static_pages#about'
  
  get 'sessions/new'

  get 'users/new'

  get 'signup'  => 'users#new'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  
  resources :users
  resources :items
  
  

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
   # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  
  def add
    # get the ID of the product
	id = params[:id]
    
	# if the cart has already been created, use the existing cart
	# else create a blank cart
	if session[:cart] then
		cart = session[:cart]
	else
		session[:cart] = {}
		cart = session[:cart]
	end
	
	# if the product has alreadd been added to the cart, increment the value
	# else set the value to 1
    	if cart[id] then
		cart[id] = cart[id] + 1
	else
		cart[id] = 1
	end
	
	# redirect to the cart display page
   	 redirect_to :action => :index
  end #end add method 

  def clearCart
    	# set the session variable to nil and redirect
    	session[:cart] = nil
	redirect_to :action => :index
  end

  def index
	# if there is a cart, pass it to the page for display
	# else pass an empty value
    	if session[:cart] then
		@cart = session[:cart]
	else
		@cart = {}
	end
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :director, :country, :genre, :description, :image_url, :price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
    session[:user_id] = nil
    session[:cart] = nil
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Oh Cinema!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
    
    
  end
  
   # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
   # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/cart/index.html.erb
<div class="container">
<h1>Your Cart</h1>

<% if @cart.empty? %>
    <h3>Your Cart is empty.<h3>
<% else %>

<% total = 0 %>

<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading"><h3>Items in your cart</h3></div>
	
      <table class="table">
        <tr>
          <td class="legend"></td>
          <td class="legend">Item</td>
          <td class="legend">Price</td>
          <td class="legend">Qty</td>
          <td class="legend">Total</td>
        </tr>

    <% @cart.each do | id, quantity | %>
        <% item = Item.find_by_id(id) %>
        <tr>
          <td>
            <div class="image">
                    <%= (image_tag item.image_url, :style => "height:200px") %>
            </div>
          </td>
          <td class="title"><h4><%= item.title  %></h4></td>
          <td class="price"><%= number_to_currency(item.price) %></td>
          <td class="quantity"><%= quantity %><br /></td>
          <td class="price">
            <%= number_to_currency(quantity * item.price, :unit => "£") %>
          </td>
        </tr>
        <% total += quantity * item.price %>
    <% end %>

        <tr>
          <td colspan="4">
            <div class="total">Total:</div>
          </td>
          <td>
            <div class="price"><%= number_to_currency(total, :unit => "€") %></div>
          </td>
        </tr>
      </table>
      
  </div>

<% end %>

    <button type="button" class="btn btn-default"><%= link_to 'Continue Shopping', :controller => :items %></button>
    <button type="button" class="btn btn-default"><%= link_to 'Clear Cart', cart_clear_path %></button>
              <!-- Trigger the modal with a button -->
                  <button type="button" class="btn btn-info primary" data-toggle="modal" data-target="#myModal">PROCEED TO CHECKOUT</button>
                  <!-- Modal -->
                  <div class="modal fade" id="myModal" role="dialog">
                    <div class="modal-dialog modal-lg">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">Opps! Not me again!</h4>
                        </div>
                        <div class="modal-body">
                          <p>Unforunately this action can not be completed at this time.</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
</div>

</div>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="jumbotron">
  <div class="container">
  
    <img alt="Oh Cinema" src="../assets/logo.png">
  <!--<h1>Welcome to Oh Cinema!</h1>-->
  <h2>Amazing Movies. Amazing Prices</h2>
  
  <p><%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %></p>
  </div>
</div>

<p id="notice"><%= notice %></p>


<div class="container">
<div class="panel panel-primary">
    <div class="panel-heading"><h3>Catalogue</h3></div>

<table class="table">


<% @items.each do |item| %>
  <tr>
    <td>
        <div class="image">
            <%= (image_tag item.image_url, :style => "height:300px") %>
        </div>
    </td>
    <td>
        <div class="title">
            <h2><%= item.title %></h2>
        </div>
         <div class="info">
            Director: <%= item.director %>
       
            Genre: <%= item.genre  %>
       
            Country: <%=  item.country %>
        </div>
        
        <div class="description">
            <%=h item.description %>
        </div>
        <div class="price">
           <h4>Price: <%= number_to_currency(item.price, :unit => "€") %></h4>
        </div>
        <div class="links">
            <% if logged_in? == true %>
              <a href="/cart/<%= item.id %>" class="btn btn-primary" role="button">Add to Cart</a><br><br>
            
              <% else %>
              
              <!-- Trigger the modal with a button -->
                  <button type="button" class="btn btn-info primary" data-toggle="modal" data-target="#myModal">Add to Cart</button>
                  <!-- Modal -->
                  <div class="modal fade" id="myModal" role="dialog">
                    <div class="modal-dialog modal-lg">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">Login required to complete this action</h4>
                        </div>
                        <div class="modal-body">
                          <p>You must be logged into your <i>Oh Cinema!</i> account to add products to your basket. Don't worry, <%= link_to "You can login here.", login_path %></p>
                          <p>Not a user? <%= link_to "Sign up now! It only takes a second", signup_path %></p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>

            <% end %>

        </div>
    </td>
  </tr>

<% end %>
</table>
  
  
</div>
</div>

app/views/items/index.html.foradmin.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Director</th>
      <th>Country</th>
      <th>Genre</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.director %></td>
        <td><%= item.country %></td>
        <td><%= item.genre %></td>
        <td><%= item.description %></td>
        <td><%= item.image_url %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>
<div class="container">
<%= render 'form' %>

<%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<div class = "container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Director:</strong>
  <%= @item.director %>
</p>

<p>
  <strong>Country:</strong>
  <%= @item.country %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @item.genre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>
</div>

app/views/layouts/_footer.html.erb
<div id='footer'>
   <h6 class="footertext">&copy; Thomas Mooney 2015</h6>
</div>
  

app/views/layouts/_header.html.erb
<!-- menu code -->
<nav class="navbar navbar-inverse">    
    <div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>                        
			</button>
				<a class="navbar-brand" href="/items"><img alt="Oh Cinema" src="../assets/brand.png"></a>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to '<i class="glyphicon glyphicon-home"></i> Home'.html_safe,    items_path %></li>
				<li><%= link_to '<i class="glyphicon glyphicon-shopping-cart"></i> Basket'.html_safe, cart_path %></li>
				<li><%= link_to '<i class="glyphicon glyphicon-info-sign"></i> About'.html_safe,    about_path %></li>
			
			<!-- menu appears different dependng on whether you are logged in or not -->
			<% if logged_in? %>
		      	<li><%= link_to '<i class="glyphicon glyphicon-log-out"></i> Logout'.html_safe, logout_path, method: "delete" %></li>
			<% else %>
            <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i> Login'.html_safe, login_path %></li>
      <% end %>
		  	  </ul>
		</div>
	 </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oh Cinema!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'ohicon.png' %>
</head>

<body>
	<%= render 'layouts/header' %>
	
 
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
      
   	<%= yield %>
   	
 	
 	<%= render 'layouts/footer' %>
 
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<div class="jumbotron">
  <div class="container">
  <h1>About Oh Cinema!</h1>
  <p>Browse throught our amazing collection of movies from all over the world & Sign up for an account to hear about our latest great deals and offers</p>
  <p><%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %></p>
  </div>
</div>

<div class="container">

  <div class="about"><h1>Find us in store</h1>
    <p>In addition to our online store we have a store located in the heart of Dublin city centre. Whether you're a local or just visting, drop in. </p>
    <p>You can find us at:</p>
    <h3>17/19 Wexford Steet, Dublin 2</h3>
    <h3>Opening Hours</h3>
    <p>Monday - Fri: 09:00 - 17:00</p>
    <p>Saturday: 10:00 - 20:00</p>
    <p>Sunday: 10:00 - 17:0</p>
  </div>

  <div class="about2">
    <div class="row">
      <div class="col-sm-6">
       <h3>Email: enquiries@ohcinema.com</h3>
      </div>
      <div class="col-sm-6">
        <h3>Phone: (353) 555-6767</h3>
      </div>
    </div>
  </div>


</div>

app/views/users/new.html.erb
<div class="container">
<h1>Sign up</h1>

<div class "container"></div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      </section>
       <section class="links_info">
      <p>
       <%= link_to 'Continue Shopping', :controller => :items %> |  <%= link_to 'View Cart', :controller => :cart %> 
      </p>
      <p>
      
      </p>
       
    </section>
  </aside>
  
</div>
</div>